dice: Add device id certificate chain utility
Introduce a Python utility to verify the PFR device ID certificate
chain generated during the manufacturing process. This tool provides
the following features:

- Verify devie id certificate chain by checking magic number, type,
  and hash
- Display certificate details with proper formatting

Usage:

  python3 certchain_utility.py verify certchain.bin

Result:

- Success

  ==========  Magic Number:
  0x43455254

  ==========  Data Length:
  0x66d

  ==========  Hash Value:
  c3 35 6d 7f 78 bf 41 a7 09 2e f1 03 cd 69 74 cd
  ad e0 1b 7f dc dd 58 41 ff 2a 9b f1 7f 31 87 1a

  ==========  Public Key:
  04 95 b1 cc d0 bc 45 26 9e 1a 86 06 da f1 4e 3d
  5c 21 b3 15 59 eb ae f4 aa 66 ff 9b 4c 9c 0c 3d
  d0 98 ef 8a e0 e8 d1 04 bc 58 ed 72 49 ab 8d a7
  42 6d 72 bf a3 a5 51 59 f4 5a 2c 8d 1f 78 71 df
  e4 52 56 94 36 7e f8 62 82 50 c0 af 03 bb ac 86
  31 6a 02 4b 5b ac 63 05 0e 53 a1 68 18 0e eb d0
  54

  ==========  Certificate Type:
  0

  Certchain file verified successfully

- Failure:

  Error: Hash mismatch

  Expected:
  74 b2 77 e6 52 89 b0 18 79 f6 27 31 74 ea 0f a7
  ef c0 08 53 f7 ea 5d 81 fc bf 8e c8 e2 ae d4 5e

  Actual:
  c3 35 6d 7f 78 bf 41 a7 09 2e f1 03 cd 69 74 cd
  ad e0 1b 7f dc dd 58 41 ff 2a 9b f1 7f 31 87 1a

Signed-off-by: Steven Lee <steven_lee@aspeedtech.com>
Change-Id: I31abe1157679daf6a16302af2391bc8674936d2d